### ISSUE TITLE
Having the mod enabled causes fps fix mods to not work

### ISSUE THREAD

**Issue by schlipschlop** [Moffein/Starstorm2Unofficial#19]
Having the videogame mod 2 unofficial mod enabled causes FPS fix mods not to work. With it enabled, everything becomes attached to FPS again, as if the FPS fix mods were not there. Disabling it causes FPS fixes to work again.

**Comment by Moffein** [comment]
Could you post your log when you get the chance?
You can find it by going to r2modman -> settings -> locations -> Browse Profile Folder -> BepInEx/LogOutput.log

**Comment by Moffein** [comment]
I've looked into the issue, and while I can't figure out why it's happening, going into the r2modman config editor, opening RoR2BepInExPack.cfg, and enabling "Fix Frame Dependent Logic" fixes it.
I've been running the game with this config option enabled this whole time, which is why the bugs never showed up for me.

**Comment by Moffein** [comment]
I've uploaded a fix for the issue on Thunderstore.
