### ISSUE TITLE
No nemesis commando?

### ISSUE THREAD

**Issue by nicstaley** [Moffein/Starstorm2Unofficial#22]
Only nemesis enforcer spawns when exiting the void fields and I cannot see nemesis commando or the executioner in character select. Do I need to have this mod _and_ the old deprecated StarStorm 2 installed?

**Comment by Moffein** [comment]
The deprecated SS2 is not needed and will completely break your game if it is installed since it isn't updated.
Post your log and I'll take a look. You can find it by going to Settings -> Locations -> Browse Profile Folder -> BepInEx/LogOutput.log

Keep in mind that if you have Survariants installed, Nemesis Commando will be listed under the Commando variants.

**Comment by nicstaley** [comment]
Thank you for responding so quickly. I was advised by the modding discord to go into the config (I was unaware how to do that before) and Nemesis Commando, Executioner, and Chirr were all disabled for some reason. I had never altered any settings after I installed the mod. It automatically unlocked Nemesis Commando once I activated him in the config. Is the proper way to unlock him just to do the Void Fields?

**Comment by Moffein** [comment]
If you installed this mod through a modpack, it may have come with the config pre-set.
Normally, you unlock Nemesis Commando by completing the Void Fields, then defeating him in the following Invasion event.
If you have the Force Unlock option enabled in the config, he'll be unlocked automatically.
